version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    env_file:
      - ./docker-env/.env.prod
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    networks:
      - app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
