version: '3.8'

services:

  web:
    container_name: be-challenge-revenue
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    env_file:
      - ./docker-env/.env.prod
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: be-challenge-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./docker-env/.env.prod
    networks:
      - app

  nginx:
    container_name: be-challenge-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
