swagger: "2.0"
info:
  description: "Thisi is a sample api for BE Receipt Challenge"
  version: "1.0.0"
  title: "Swagger BE Nory"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "sales"
  description: "View your sales"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /sales/hourly:
    get:
      tags:
      - "hourly"
      summary: "Hourly breakdown"
      description: "Get an hourly breakdown of daily sales for a brand"
      operationId: "getHourlySales"
      produces:
      - "application/json"
      parameters:
      - name: "brand_id"
        in: "query"
        description: "ID of brand"
        required: true
        type: "string"
      - name: "start"
        in: "query"
        description: "start date in RFC-3339 format, e.g. 2017-07-21"
        required: true
        type: "string"
        format: "date"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/HourlyData"
        "400":
          description: "Invalid date or missing parameters"
        "404":
          description: "Brand ID not found"
  /sales/daily:
    get:
      tags:
      - "daily"
      summary: "Daily breakdown"
      description: "Get an daily breakdown of sales for a brand"
      operationId: "getDailySales"
      produces:
      - "application/json"
      parameters:
      - name: "brand_id"
        in: "query"
        description: "ID of brand"
        required: true
        type: "string"
      - name: "start"
        in: "query"
        description: "start date in RFC-3339 format, e.g. 2017-07-21. Inclusive"
        required: true
        type: "string"
        format: "date"
      - name: "end"
        in: "query"
        description: "end date in RFC-3339 format, e.g. 2017-07-21. Inclusive"
        required: true
        type: "string"
        format: "date"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DailyData"
        "400":
          description: "Invalid date or missing parameters"
        "404":
          description: "Brand ID not found"
definitions:
  DailyData:
    type: "object"
    properties:
      branch_id:
        type: "string"
      daily_breakdown:
        type: "array"
        items:
          $ref: "#/definitions/DailyEntry"
      end:
        type: "string"
        format: "date-time"
      start:
        type: "string"
        format: "date-time"
      total:
        type: "number"
        format: "float"
        description: "Sum of all daily sales"
  DailyEntry:
    type: "object"
    additionalProperties:
      type: "number"
      format: float
  HourlyData:
    type: "object"
    properties:
      branch_id:
        type: "string"
      daily_breakdown:
        type: "array"
        items:
          $ref: "#/definitions/HourlyEntry"
      end:
        type: "string"
        format: "date-time"
      start:
        type: "string"
        format: "date-time"
      total:
        type: "number"
        format: "float"
        description: "Sum of all daily sales"
  HourlyEntry:
    type: "object"
    additionalProperties:
      type: "number"
      format: float

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"